### ISSUE TITLE
Relocation truncated to fit R_X86_64_32S failed

### ISSUE THREAD

**Issue by ardhipoetra** [ardhipoetra/faasm#3]
Despite invoking `demo/hello` is successful on sconified-worker, invoking other application (for example, `demo/c_example`) produces this error : 
```
...
[12:15:00] [50] [T] Getting S3 key faasm/demo/c_example/function.aot as bytes
[12:15:00] [50] [T] Caching S3 key faasm/demo/c_example/function.aot at /usr/local/faasm/object/demo/c_example/function.aot
[12:15:00] [50] [T] WAMR loading 57636 wasm bytes

[12:15:00] [50] [E] Failed to load WAMR module: 
AOT module load failed: relocation truncated to fit R_X86_64_32S failed. Try using wamrc with --size-level=1 option.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load WAMR module
Caught stack backtrace:
[SCONE|DEBUG] src/enclave/enclave.c:1381:_enclave_terminate(): FSPF Synchronization Point: Persisting FSPF data before terminating enclave due to unhandled signal 6
...
```

The message comes from `./core/iwasm/aot/arch/aot_reloc_x86_64.c`, line 198 : https://github.com/faasm/wasm-micro-runtime/blob/5e9dc3c7eb33167389d99b7e5851dc55b5911d33/core/iwasm/aot/arch/aot_reloc_x86_64.c#L198 

Question : what is "relocation" mean in this case? Why we want to  relocate to 32-bit? 

Pinging @csegarragonz since you might know something.

**Comment by ardhipoetra** [comment]
Commit https://github.com/ardhipoetra/faasm/commit/4d185f43407ad02f1dc41d3f4b031f715960dc07 closes this issue. On SGX, size-level needs to 1 (?).

Source : https://github.com/bytecodealliance/wasm-micro-runtime/issues/2274

**Comment by csegarragonz** [comment]
Yes, you can see this in the code generation step for SGX here: https://github.com/faasm/faasm/blob/main/src/wamr/codegen.cpp#L76-L79
